name: 美妙松鼠洞
favicon: null
layout_spectrum: 0.79135
typography_spectrum: 0.24695
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#807f87'
    - '#c99510'
    - '#3c463f'
    - '#ba3c05'
    - '#690406'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
