name: 美妙松鼠洞SquirrelHole
favicon: null
layout_spectrum: 0.055667412700131536
typography_spectrum: 0.8200715745333582
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8478364679031074
  lightness: 0.4940662186127156
  saturation: 0.21314443461596966
  rhythmicContrast: 0.9557511110324413
purpose: []
